services:
  app:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    restart: unless-stopped
    env_file: 
      - .env
    ports:
      - "${SERVER_PORT}:8501"
    volumes:
      - ./config.yaml:/app/config.yaml
